// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLvkeP5mWnHe8z_TWJD97-zJk29gklfHI',
    appId: '1:989134311482:web:707c8ac9040bcf0ccc2503',
    messagingSenderId: '989134311482',
    projectId: 'e-insights-uae',
    authDomain: 'e-insights-uae.firebaseapp.com',
    storageBucket: 'e-insights-uae.firebasestorage.app',
    measurementId: 'G-06YYF99T3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPrlhvEW4Ar1nzBbhCdAokx5at453pamA',
    appId: '1:989134311482:android:fd4fcb7526b4dee3cc2503',
    messagingSenderId: '989134311482',
    projectId: 'e-insights-uae',
    storageBucket: 'e-insights-uae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALcsI3HY95A3MQREqDq-nQwT_mkVFnGPk',
    appId: '1:989134311482:ios:9c0b2272818d4c0dcc2503',
    messagingSenderId: '989134311482',
    projectId: 'e-insights-uae',
    storageBucket: 'e-insights-uae.firebasestorage.app',
    iosBundleId: 'com.example.eInsights',
  );
}
